export type Lang = 'ru' | 'tr';

const dict = {
  ru: {
    dashboard: 'Главная', profile: 'Профиль', analytics: 'Аналитика', products: 'Товары', invoices: 'Накладные', chat: 'Чат', employees: 'Сотрудники', logout: 'Выйти',
    wholesale: 'Оптовые продажи', openProfile: 'Открыть профиль', notifications: 'Уведомления', noNew: 'Новых нет', newFromChat: 'новых из чата', chatNotifications: 'Уведомления чата', noNotifications: 'Пока нет уведомлений', voiceMessage: 'Голосовое сообщение', file: 'Файл', attachment: 'вложение',
    loginTitle: 'Вход в систему', loginSubtitle: 'Доступ только для владельца и сотрудников', email: 'Email', password: 'Пароль', signIn: 'Войти', publicRegistrationOff: 'Публичная регистрация отключена. Сотрудников добавляет только владелец во вкладке «Сотрудники».', dataInBrowser: 'Данные хранятся в вашем браузере', enterEmail: 'Введите email', invalidEmail: 'Некорректный email', enterPassword: 'Введите пароль', min6: 'Минимум 6 символов', welcome: 'Добро пожаловать!',
    hello: 'Добро пожаловать', invoiceCount: 'Накладные', totalCreated: 'создано всего', salesUsd: 'Продажи USD', salesRub: 'Продажи RUB', byInvoices: 'сумма по накладным', byRates: 'по введённым курсам', recentInvoices: 'Последние накладные', all: 'Все', number: 'Номер', client: 'Клиент', rate: 'Курс', status: 'Статус',
    manageProducts: 'Управление прайс-листом тканей', addProduct: 'Добавить товар', noProducts: 'Нет товаров', addFirstProduct: 'Добавьте первый товар для работы с накладными', add: 'Добавить', name: 'Название', composition: 'Состав', price: 'Цена', density: 'Плотность', actions: 'Действия', editProduct: 'Редактировать товар', fabricName: 'Название ткани', cancel: 'Отмена', save: 'Сохранить', deleteProductQ: 'Удалить товар?', deleteProductText: 'Товар будет удалён из прайс-листа. Уже созданные накладные сохранят данные о нём.', delete: 'Удалить',
    createInvoice: 'Создать накладную', salesManagement: 'Создание и управление продажами', noInvoices: 'Нет накладных', createInvoiceHint: 'Создайте накладную с несколькими позициями, курсом USD и расчётом RUB', date: 'Дата', print: 'Печать', deleteInvoiceQ: 'Удалить накладную?', deleteInvoiceText: 'Действие нельзя отменить. Аналитика будет пересчитана автоматически.',
    newInvoice: 'Новая накладная', fillInvoice: 'Заполните данные и добавьте позиции', noProductsInPrice: 'Нет товаров в прайс-листе', beforeInvoice: 'перед созданием накладной', clientName: 'Имя / компания', extraInfo: 'Доп. информация', invoiceLines: 'Позиции накладной', positionLine: 'Позиция', product: 'Товар', chooseProduct: 'Выберите товар', quantity: 'Кол-во', total: 'Итого', totalAmount: 'Общая сумма', invoiceNotFound: 'Накладная не найдена', backToList: 'К списку', preparing: 'Готовлю...', invoiceStatus: 'Статус накладной', lines: 'Позиции', priceUsd: 'Цена USD', priceRub: 'Цена RUB', totalUsd: 'Итого USD', totalRub: 'Итого RUB',
    analyticsSubtitle: 'Все показатели считаются из реальных накладных', excelReport: 'Excel отчёт', paid: 'Оплачено', kg: 'Килограммы', avgRate: 'Средний курс', totalWeight: 'общий вес', avgRateSub: 'USD/RUB по накладным', managerSales: 'Продажи по менеджерам', monthMetrics: 'Показатели за выбранный месяц', noManagerSales: 'Нет продаж менеджеров за выбранный месяц', manager: 'Менеджер', topProducts: 'Топ товаров', topClients: 'Топ клиентов', noSalesData: 'Нет данных о продажах', noClientData: 'Нет данных о клиентах', share: 'Доля',
    chatSubtitle: 'Внутренняя связь руководства и менеджеров', dialogs: 'Диалоги', generalChat: 'Общий чат', managementAndManagers: 'Руководство и менеджеры', management: 'Руководство', noMessages: 'Сообщений пока нет', firstMessage: 'Напишите первое сообщение в этот диалог', messagePlaceholder: 'Введите сообщение...', recording: 'Запись...', send: 'Отправить', edited: 'изменено', edit: 'редактировать', fileSent: 'Файл отправлен', voiceSent: 'Голосовое сообщение отправлено', micNoAccess: 'Нет доступа к микрофону', browserNoVoice: 'Браузер не поддерживает запись голосовых сообщений', fileTooBig: 'Файл слишком большой. Максимум 5 МБ', fileAttachError: 'Не удалось прикрепить файл',
    profileSubtitle: 'Ваши данные и контактная информация', fullName: 'Имя и фамилия', phone: 'Телефон', position: 'Должность', emailLoginInfo: 'Email используется для входа и сейчас не редактируется.', updateProfile: 'Сохранить', passwordChange: 'Смена пароля', passwordChangeHint: 'После смены используйте новый пароль при следующем входе.', currentPassword: 'Текущий пароль', newPassword: 'Новый пароль', repeatPassword: 'Повторите новый пароль', changePassword: 'Изменить пароль', profileUpdated: 'Профиль обновлён', passwordChanged: 'Пароль изменён', wrongCurrentPassword: 'Текущий пароль указан неверно', passwordsMismatch: 'Новый пароль и подтверждение не совпадают',
    employeesSubtitle: 'Публичная регистрация закрыта. Доступ выдаёте только вы.', accessDeniedOwner: 'Доступ к сотрудникам есть только у владельца.', employeeName: 'Имя', employeeAdded: 'Сотрудник добавлен', employeeDeleted: 'Сотрудник удалён', noEmployees: 'Сотрудников пока нет', active: 'Активен', disabled: 'Отключён', disable: 'Отключить', enable: 'Включить', deleteEmployeeQ: 'Удалить сотрудника?', deleteEmployeeText: 'Сотрудник больше не сможет войти в систему. Уже созданные им накладные останутся в базе.',
    draft: 'Черновик', processing: 'В обработке', shipped: 'Отгружено', cancelled: 'Отменено', step: 'Шаг', buyUsd: 'Купить USD', commercialRateLoading: 'обновление коммерческого курса...', commercialRateUnavailable: 'курс покупки недоступен', commercialRateCached: 'показан последний коммерческий курс', commercialBankRate: 'коммерческий курс банка', updated: 'обновлено',
  },
  tr: {
    dashboard: 'Ana sayfa', profile: 'Profil', analytics: 'Analitik', products: 'Ürünler', invoices: 'İrsaliyeler', chat: 'Sohbet', employees: 'Çalışanlar', logout: 'Çıkış',
    wholesale: 'Toptan satış', openProfile: 'Profili aç', notifications: 'Bildirimler', noNew: 'Yeni yok', newFromChat: 'sohbetten yeni', chatNotifications: 'Sohbet bildirimleri', noNotifications: 'Henüz bildirim yok', voiceMessage: 'Sesli mesaj', file: 'Dosya', attachment: 'ek',
    loginTitle: 'Sisteme giriş', loginSubtitle: 'Sadece yönetici ve çalışanlar için erişim', email: 'Email', password: 'Şifre', signIn: 'Giriş yap', publicRegistrationOff: 'Açık kayıt kapalı. Çalışanları sadece yönetici “Çalışanlar” bölümünden ekler.', dataInBrowser: 'Veriler tarayıcınızda saklanır', enterEmail: 'Email girin', invalidEmail: 'Geçersiz email', enterPassword: 'Şifre girin', min6: 'En az 6 karakter', welcome: 'Hoş geldiniz!',
    hello: 'Hoş geldiniz', invoiceCount: 'İrsaliyeler', totalCreated: 'toplam oluşturuldu', salesUsd: 'USD satış', salesRub: 'RUB satış', byInvoices: 'irsaliyeler toplamı', byRates: 'girilen kurlara göre', recentInvoices: 'Son irsaliyeler', all: 'Tümü', number: 'Numara', client: 'Müşteri', rate: 'Kur', status: 'Durum',
    manageProducts: 'Kumaş fiyat listesini yönetme', addProduct: 'Ürün ekle', noProducts: 'Ürün yok', addFirstProduct: 'İrsaliyeler için ilk ürünü ekleyin', add: 'Ekle', name: 'Ad', composition: 'İçerik', price: 'Fiyat', density: 'Gramaj', actions: 'İşlemler', editProduct: 'Ürünü düzenle', fabricName: 'Kumaş adı', cancel: 'İptal', save: 'Kaydet', deleteProductQ: 'Ürün silinsin mi?', deleteProductText: 'Ürün fiyat listesinden silinecek. Oluşturulmuş irsaliyelerdeki veriler korunur.', delete: 'Sil',
    createInvoice: 'İrsaliye oluştur', salesManagement: 'Satış oluşturma ve yönetme', noInvoices: 'İrsaliye yok', createInvoiceHint: 'Birden fazla pozisyon, USD kuru ve RUB hesabı ile irsaliye oluşturun', date: 'Tarih', print: 'Yazdır', deleteInvoiceQ: 'İrsaliye silinsin mi?', deleteInvoiceText: 'Bu işlem geri alınamaz. Analitik yeniden hesaplanır.',
    newInvoice: 'Yeni irsaliye', fillInvoice: 'Bilgileri doldurun ve kalemleri ekleyin', noProductsInPrice: 'Fiyat listesinde ürün yok', beforeInvoice: 'irsaliye oluşturmadan önce', clientName: 'Ad / şirket', extraInfo: 'Ek bilgi', invoiceLines: 'İrsaliye kalemleri', positionLine: 'Kalem', product: 'Ürün', chooseProduct: 'Ürün seçin', quantity: 'Miktar', total: 'Toplam', totalAmount: 'Genel toplam', invoiceNotFound: 'İrsaliye bulunamadı', backToList: 'Listeye dön', preparing: 'Hazırlanıyor...', invoiceStatus: 'İrsaliye durumu', lines: 'Kalemler', priceUsd: 'USD fiyatı', priceRub: 'RUB fiyatı', totalUsd: 'Toplam USD', totalRub: 'Toplam RUB',
    analyticsSubtitle: 'Tüm göstergeler gerçek irsaliyelerden hesaplanır', excelReport: 'Excel raporu', paid: 'Ödendi', kg: 'Kilogram', avgRate: 'Ortalama kur', totalWeight: 'toplam ağırlık', avgRateSub: 'İrsaliyelerde USD/RUB', managerSales: 'Yönetici satışları', monthMetrics: 'Seçilen ay göstergeleri', noManagerSales: 'Seçilen ay için yönetici satışı yok', manager: 'Yönetici', topProducts: 'En iyi ürünler', topClients: 'En iyi müşteriler', noSalesData: 'Satış verisi yok', noClientData: 'Müşteri verisi yok', share: 'Pay',
    chatSubtitle: 'Yönetim ve yöneticiler için iç iletişim', dialogs: 'Diyaloglar', generalChat: 'Genel sohbet', managementAndManagers: 'Yönetim ve yöneticiler', management: 'Yönetim', noMessages: 'Henüz mesaj yok', firstMessage: 'Bu diyaloğa ilk mesajı yazın', messagePlaceholder: 'Mesaj yazın...', recording: 'Kayıt...', send: 'Gönder', edited: 'düzenlendi', edit: 'düzenle', fileSent: 'Dosya gönderildi', voiceSent: 'Sesli mesaj gönderildi', micNoAccess: 'Mikrofona erişim yok', browserNoVoice: 'Tarayıcı ses kaydını desteklemiyor', fileTooBig: 'Dosya çok büyük. Maksimum 5 MB', fileAttachError: 'Dosya eklenemedi',
    profileSubtitle: 'Bilgileriniz ve iletişim detayları', fullName: 'Ad Soyad', phone: 'Telefon', position: 'Pozisyon', emailLoginInfo: 'Email giriş için kullanılır ve şu anda değiştirilemez.', updateProfile: 'Kaydet', passwordChange: 'Şifre değiştirme', passwordChangeHint: 'Değişiklikten sonra sonraki girişte yeni şifreyi kullanın.', currentPassword: 'Mevcut şifre', newPassword: 'Yeni şifre', repeatPassword: 'Yeni şifreyi tekrar girin', changePassword: 'Şifreyi değiştir', profileUpdated: 'Profil güncellendi', passwordChanged: 'Şifre değiştirildi', wrongCurrentPassword: 'Mevcut şifre yanlış', passwordsMismatch: 'Yeni şifre ve tekrar eşleşmiyor',
    employeesSubtitle: 'Açık kayıt kapalı. Erişimi sadece siz verirsiniz.', accessDeniedOwner: 'Çalışanlara sadece yönetici erişebilir.', employeeName: 'Ad', employeeAdded: 'Çalışan eklendi', employeeDeleted: 'Çalışan silindi', noEmployees: 'Henüz çalışan yok', active: 'Aktif', disabled: 'Devre dışı', disable: 'Devre dışı bırak', enable: 'Etkinleştir', deleteEmployeeQ: 'Çalışan silinsin mi?', deleteEmployeeText: 'Çalışan artık sisteme giremeyecek. Oluşturduğu irsaliyeler veritabanında kalır.',
    draft: 'Taslak', processing: 'İşlemde', shipped: 'Sevk edildi', cancelled: 'İptal', step: 'Adım', buyUsd: 'USD al', commercialRateLoading: 'ticari kur güncelleniyor...', commercialRateUnavailable: 'alış kuru kullanılamıyor', commercialRateCached: 'son ticari kur gösteriliyor', commercialBankRate: 'bankanın ticari kuru', updated: 'güncellendi',
  },
} as const;

export type TKey = keyof typeof dict.ru;
export const t = (lang: Lang, key: TKey) => dict[lang][key] || dict.ru[key] || key;
